apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image:  {{ .Values.images.scheduler }}
          ports:
            - name: app
              containerPort: 4001
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ .Values.supabaseDatabase.url }}:{{ .Values.supabaseDatabase.port }}/{{ .Values.supabaseDatabase.dbName }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
      imagePullSecrets: {{- .Values.imagePullSecrets | toYaml | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: scheduler
  ports:
    - port: 80
      targetPort: app
      protocol: TCP
