apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-actions-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: rasa-actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa-actions
  template:
    metadata:
      labels:
        app: rasa-actions
    spec:
      containers:
        - name: rasa-actions
          image: {{ .Value.images.rasaActions }}
          ports:
            - name: app
              containerPort: 5055
          env:
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.youtubeApiSecret.name }}
                  key: {{ .Values.youtubeApiSecret.key }}
            - name: OPENWEATHERMAP_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.openweathermapSecret.name }}
                  key: {{ .Values.openweathermapSecret.key }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "125m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
      imagePullSecrets: {{- .Values.imagePullSecrets | toYaml | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-actions-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: rasa-actions
  ports:
    - port: 80
      targetPort: app
      protocol: TCP
